# Generated by Django 5.2.3 on 2025-06-28 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адреса')),
                ('description', models.TextField(verbose_name='Опис')),
                ('type', models.CharField(choices=[('room', 'Кімната'), ('desk', 'Робоче місце'), ('hall', 'Конференц-зал')], max_length=20, verbose_name='Тип')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вмістимість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступний')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Простір',
                'verbose_name_plural': 'Простори',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Сповіщення')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
